<table width="600" id="wrapper" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;" >
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="header" width="600" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="icon" width="275" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;width:275px;text-align:center;" >
                        <a href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;display:block;text-indent:-9999px;overflow:hidden;background-image:url('images/logo.jpg');width:238px;height:27px;margin-top:0;margin-bottom:0;margin-right:auto;margin-left:auto;" >READY-TO-WEAR.RU</a>
                    </td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Новинки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Одежда</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Обувь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Сумки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Аксессуары</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Sale</a></td>
            </tr></table>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <span class="header" style="font-family:Arial, Helvetica, sans-serif;display:block;margin-top:40px;margin-left:19px;font-size:16px;line-height:24px;width:350px;" >Уважаемый <strong style="font-family:Arial, Helvetica, sans-serif;" >Иванов Андрей</strong>, мы можем вам чем-то помочь?</span>
            <hr style="font-family:Arial, Helvetica, sans-serif;margin-top:43px;margin-bottom:0;margin-right:20px;margin-left:20px;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;border-style:solid;border-top-width:0;border-color:#E9E9E9;" >
            <span class="info" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:20px;display:block;margin-top:24px;margin-bottom:0;margin-right:20px;margin-left:20px;color:#666666;" >Мы хотим поблагодарить вас за посещение <a href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;font-weight:700;" >READY-TO-WEAR.RU</a>. Мы обратили внимание,
что вы оставили покупки в своей корзине: если по каким-то причинам вам не удалось закончить свой заказ, или у вас возникли какие-либо вопросы — мы всегда готовы прийти
к вам на помощь.</span>
            <p class="btn_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-bottom:0;margin-right:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-top:22px;margin-left:20px;" ><a class="btn" href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;display:block;width:180px;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;color:#FFFFFF;padding-top:9px;padding-bottom:9px;padding-right:0;padding-left:0;text-align:center;font-size:14px;font-weight:700;" >ПЕРЕЙТИ В КОРЗИНУ</a></p>
            <hr style="font-family:Arial, Helvetica, sans-serif;margin-top:43px;margin-bottom:0;margin-right:20px;margin-left:20px;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;border-style:solid;border-top-width:0;border-color:#E9E9E9;" >
            <p class="contacts" style="font-family:Arial, Helvetica, sans-serif;margin-bottom:0;margin-right:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:11px;line-height:19px;color:#BABABA;margin-top:20px;margin-left:20px;width:330px;" >По любым вопросам вы можете обратиться к нам по телефону <span class="phone" style="font-family:Arial, Helvetica, sans-serif;color:#636363;" >8 (495) 609-69-68</span>, или же просто ответить на это письмо. </p>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="footer" width="600" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;color:#ffffff;margin-top:43px;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Помощь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Журнал</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Тренды</a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" >    </td>
                    <td class="phone" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;width:140px;text-align:left;" >+7 (495) 609-69-68</td>
                    <td class="site" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;font-weight:700;width:143px;text-align:left;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >www.ready-to-wear.ru</a></td>
                    <td class="social" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-left:0px;text-align:right;padding-right:10px;width:100px;" >
                        <a href="//ready-to-wear.ru" class="fb" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('images/fb.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="vk" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('images/vk.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="tw" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('images/tw.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="ig" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;background-image:url('images/ig.jpg');width:23px;height:16px;" ></a>
                    </td>
            </tr></table>
        </td>
    </tr>
</table>