<table width="600" id="wrapper" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;" >
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="header" width="600" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="icon" width="275" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;width:275px;text-align:center;" >
                        <a href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >
                            <img src="http://ready-emails.herokuapp.com/images/logo.jpg" alt="READY-TO-WEAR.RU" style="border:0;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;">
                        </a>
                    </td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Новинки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Одежда</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Обувь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Сумки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Аксессуары</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Sale</a></td>
                </tr></table>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="content_top" width="600" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" ><p class="header" style="font-family:Arial, Helvetica, sans-serif;display:block;margin-top:40px;margin-left:19px;font-size:16px;line-height:24px;width:350px;" >Уважаемый <strong style="font-family:Arial, Helvetica, sans-serif;" >Иванов Андрей</strong>, вы успешно зарегистрированы на READY-TO-WEAR.RU!</p></td>
                    <td width="190" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:190px;" ><p class="sign" style="font-family:Arial, Helvetica, sans-serif;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:12px;margin-top:27px;line-height:18px;" >
                            <span style="font-family:Arial, Helvetica, sans-serif;" ><strong style="font-family:Arial, Helvetica, sans-serif;" >Ваш логин:</strong> mail@gmail.com</span>
                            <br style="font-family:Arial, Helvetica, sans-serif;" >
                            <span style="font-family:Arial, Helvetica, sans-serif;" ><strong style="font-family:Arial, Helvetica, sans-serif;" >Ваш пароль:</strong> Ready12345</span>
                        </p></td>
                </tr></table>
            <p class="table_header" style="font-family:Arial, Helvetica, sans-serif;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-top:33px;margin-bottom:0;margin-right:20px;margin-left:20px;font-size:12px;" >ВАШИ НОВЫЕ ПРЕИМУЩЕСТВА:</p>
            <table id="content" width="560" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;margin-top:23px;margin-bottom:0;margin-right:20px;margin-left:20px;font-size:12px;line-height:16px;" >
                <tr class="text" style="font-family:Arial, Helvetica, sans-serif;" >
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-right:0;padding-left:0;width:33.333%;padding-bottom:50px;" >
                        <p style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-bottom:0;padding-right:0;padding-left:0;padding-top:5px;" ><em style="font-family:Arial, Helvetica, sans-serif;" >— Express checkout</em></p>
                        <p style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-bottom:0;padding-right:0;padding-left:0;padding-top:5px;" ><em style="font-family:Arial, Helvetica, sans-serif;" >— Скидки и бонусы</em></p>
                    </td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-right:0;padding-left:0;width:33.333%;padding-bottom:50px;" >
                        <p style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-bottom:0;padding-right:0;padding-left:0;padding-top:5px;" ><em style="font-family:Arial, Helvetica, sans-serif;" >— Personal Wishlist</em></p>
                        <p style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-bottom:0;padding-right:0;padding-left:0;padding-top:5px;" ><em style="font-family:Arial, Helvetica, sans-serif;" >— Easy ordering</em></p>
                    </td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-right:0;padding-left:0;width:33.333%;padding-bottom:50px;" >
                        <p style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-bottom:0;padding-right:0;padding-left:0;padding-top:5px;" ><em style="font-family:Arial, Helvetica, sans-serif;" >— Бесплатная доставка для
                                заказов на 5 000 р. и более</em></p>
                    </td>
                </tr>
                <tr class="image" style="font-family:Arial, Helvetica, sans-serif;" >
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:33.333%;text-align:center;" ><img src="http://ready-emails.herokuapp.com/images/items/girl1.png" style="font-family:Arial, Helvetica, sans-serif;" ></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:33.333%;text-align:center;" ><img src="http://ready-emails.herokuapp.com/images/items/girl2.png" style="font-family:Arial, Helvetica, sans-serif;" ></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:33.333%;text-align:center;" ><img src="http://ready-emails.herokuapp.com/images/items/girl3.png" style="font-family:Arial, Helvetica, sans-serif;" ></td>
                </tr>
            </table>
            <table id="bottom_menu" width="560" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;margin-top:0px;margin-bottom:0;margin-right:20px;margin-left:20px;font-size:11px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:42px;padding-bottom:0;padding-right:0;padding-left:0;" ><a href="" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;" ><strong style="font-family:Arial, Helvetica, sans-serif;" >СМОТРЕТЬ САЙТ</strong></a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:42px;padding-bottom:0;padding-right:0;padding-left:0;" ><a href="" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;" >ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ</a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:42px;padding-bottom:0;padding-right:0;padding-left:0;" ><a href="" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;" >НАСТРОЙКИ АККАУНТА</a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:42px;padding-bottom:0;padding-right:0;padding-left:0;" ><a href="" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;" >ОПЛАТА И ДОСТАВКА</a></td>
                </tr></table>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="footer" width="600" align="center" bgcolor="#000000" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;color:#ffffff;margin-top:43px;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Помощь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Журнал</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Тренды</a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" >&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td class="phone" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;width:140px;text-align:left;" >+7 (495) 609-69-68</td>
                    <td class="site" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;font-weight:700;width:143px;text-align:left;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >www.ready-to-wear.ru</a></td>
                    <td class="social" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-left:0px;text-align:right;padding-right:10px;width:100px;" >
                        <a href="//ready-to-wear.ru" class="fb" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/fb.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="vk" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/vk.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="tw" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/tw.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="ig" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;background-image:url('http://ready-emails.herokuapp.com/images/ig.jpg');width:23px;height:16px;" ></a>
                    </td>
                </tr></table>
        </td>
    </tr>
</table>
