<table width="600" id="wrapper" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;" >
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="header" width="600" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="icon" width="275" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;width:275px;text-align:center;" >
                        <a href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >
                            <img src="http://ready-emails.herokuapp.com/images/logo.jpg" alt="READY-TO-WEAR.RU" style="border:0;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;">
                        </a>
                    </td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Новинки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Одежда</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Обувь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Сумки</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Аксессуары</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:12px;padding-bottom:12px;padding-right:0px;padding-left:0px;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#ffffff;font-size:12px;" >Sale</a></td>
                </tr></table>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table class="big_image" width="600" height="120" align="center" background="http://ready-emails.herokuapp.com/images/top.jpg" cellpadding="0" cellspacing="0" border="0" style="border-width:0;background-image:url('http://ready-emails.herokuapp.com/images/top.jpg');height:120px;">
                <tr><td>
                        <p style="font-size:120px;line-height:120px;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;">&nbsp;</p>
                </td></tr>
            </table>
            <span class="top_image" ></span>
            <p class="header" style="font-family:Arial, Helvetica, sans-serif;display:block;margin-top:40px;margin-left:19px;font-size:16px;line-height:24px;width:350px;" >Специальное предложение по вашему заказу!</p>
            <p class="info" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:20px;display:block;margin-top:24px;margin-bottom:0;margin-right:20px;margin-left:20px;color:#666666;" > Мы очень ценим ваше посещение <a href="//READY-TO-WEAR.RU" style="font-family:Arial, Helvetica, sans-serif;color:#000000;text-decoration:none;font-weight:700;" >READY-TO-WEAR.RU</a>,
                поэтому хотим помочь вам окончательно определиться с покупками и подарить вам купон на 10% скидку на ваш незаконченный заказ.</p>
            <p class="move" style="display:block;margin-top:20px;margin-bottom:30px;margin-right:20px;margin-left:20px;font-size:12px;font-family:Arial, Helvetica, sans-serif;" >Торопитесь — купон будет действовать <strong style="font-family:Arial, Helvetica, sans-serif;" >всего 1 неделю</strong>!</p>
            <table id="discount" width="560" align="center" bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:35px;margin-right:20px;margin-left:20px;border-top-width:1px;border-top-style:solid;border-top-color:#CCC;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#CCC;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:35px;padding-bottom:40px;padding-right:0;padding-left:0;vertical-align:bottom;" >
                        <span class="name" style="font-family:Arial, Helvetica, sans-serif;font-weight:700;font-size:12px;vertical-align:bottom;" >ВАША СКИДКА НА R2W :</span>
                        <span class="discount" style="font-family:Arial, Helvetica, sans-serif;font-size:26px;padding-left:5px;line-height:21px;" >10%</span>
                    </td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:35px;padding-bottom:40px;padding-right:0;padding-left:0;vertical-align:bottom;" >
                        <span class="name" style="font-family:Arial, Helvetica, sans-serif;font-weight:700;font-size:12px;" >КОД КУПОНА :</span>
                        <span class="coupon" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;display:inline-block;padding-left:15px;" >R2W15375709990</span>
                    </td>
            </tr></table>
            <p class="btn_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-bottom:0;margin-right:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;margin-top:22px;margin-left:20px;" ><a class="btn" href="//READY-TO-WEAR.RU" style="text-decoration:none;" ><span style="font-family:Arial, Helvetica, sans-serif;text-decoration:none;display:inline-block;border-width:9px;border-style:solid;border-color:#000;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;color:#FFFFFF;padding-top:0px;padding-bottom:0px;padding-right:0;padding-left:0;text-align:center;font-size:14px;font-weight:700;">ПЕРЕЙТИ В КОРЗИНУ</span></a></p>
            <p class="contacts" style="font-family:Arial, Helvetica, sans-serif;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:11px;line-height:19px;color:#BABABA;margin-top:40px;margin-bottom:0;margin-right:20px;margin-left:20px;" >По любым вопросам вы можете обратиться к нам по телефону <span class="phone" style="font-family:Arial, Helvetica, sans-serif;color:#636363;" >8 (495) 609-69-68</span>, или же просто ответить на это письмо. </p>
        </td>
    </tr>
    <tr style="font-family:Arial, Helvetica, sans-serif;" >
        <td class="content_wrapper" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <table id="footer" width="600" align="center" bgcolor="#000000" cellpadding="0" cellspacing="0" border="0" style="border-width:0;font-family:Arial, Helvetica, sans-serif;background-color:#000000;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;color:#ffffff;margin-top:43px;font-size:12px;" ><tr style="font-family:Arial, Helvetica, sans-serif;" >
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Помощь</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Журнал</a></td>
                    <td class="menu" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >Тренды</a></td>
                    <td style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;text-align:center;" >&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td class="phone" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;width:140px;text-align:left;" >+7 (495) 609-69-68</td>
                    <td class="site" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-right:0px;padding-left:0px;font-weight:700;width:143px;text-align:left;" ><a href="//ready-to-wear.ru" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;" >www.ready-to-wear.ru</a></td>
                    <td class="social" style="font-family:Arial, Helvetica, sans-serif;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:16px;padding-bottom:16px;padding-left:0px;text-align:right;padding-right:10px;width:100px;" >
                        <a href="//ready-to-wear.ru" class="fb" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/fb.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="vk" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/vk.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="tw" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;width:19px;height:16px;background-image:url('http://ready-emails.herokuapp.com/images/tw.jpg');" ></a>
                        <a href="//ready-to-wear.ru" class="ig" style="font-family:Arial, Helvetica, sans-serif;color:#ffffff;text-decoration:none;display:inline-block;background-image:url('http://ready-emails.herokuapp.com/images/ig.jpg');width:23px;height:16px;" ></a>
                    </td>
                </tr></table>
        </td>
    </tr>
</table>
